# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jemoji]

# Setup
title:            Jonas Lehnert
tagline:          "Personal Website"
description:      "Postdoctoral fellow at the University of Ottawa"
url:              http://jonaslehnert.github.io
baseurl:          /

paginate:         3

email: jlehnert@uottawa.ca
linkedin: https://www.linkedin.com/in/jonaslehnert
github: https://github.com/jonaslehnert
